FROM node:20.12.0-slim

WORKDIR /usr/src/app

# Copy entire monorepo, not just root files
COPY . .

# Install deps across all workspaces
RUN npm install

# Sanity check: Make sure Next.js exists
RUN npm ls next

# Generate Prisma client
RUN npm run db:generate

# Start the user app
CMD ["npm", "run", "start-user-app"]
