name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile.user
        push: true
        tags: vishalsingh2972/week-18-ci-cd:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull vishalsingh2972/week-18-ci-cd:latest  # Replace with your Docker Hub username and repository

    - name: Deploy to EC2 # instead  of this step "Deploy to EC2" we can also do elastic beanstalk (good for autoscaling applications)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull vishalsingh2972/week-18-ci-cd:latest
          sudo docker stop web-app || true                       
          sudo docker rm web-app || true                           
          sudo docker run -d --name web-app --restart always -p 3005:3000 vishalsingh2972/week-18-ci-cd:latest 

        #// pull the latest image from docker hub
        #// stop the web-app exisitng container (if any)
        #// remove the web-app exisitng container (if any)
        #// start a new web-app container but now within the ec2 instance , here need to add db creds

